`default_nettype none
// =============================================================================
// Module: market_parser_100g_cmac_ip_strategy_top
// =============================================================================
// Generated AMD CMAC UltraScale+ AXIS IP boundary for the strategy path.
//
// This wrapper instantiates the generated `cmac_usplus_0` AXIS-mode IP and
// feeds its no-backpressure RX AXIS stream into the owned packet-to-book path.
// It is intentionally receive-focused: TX AXIS is held idle and board-specific
// management/DRP policy stays outside this first integration shell.
module market_parser_100g_cmac_ip_strategy_top #(
    parameter logic [15:0] FEED_UDP_PORT           = 16'd5000,
    parameter logic [15:0] TARGET_STOCK_LOCATE     = 16'h1234,
    parameter int          CMAC_RX_FIFO_DEPTH      = 16,
    parameter int          STRIP_FIFO_DEPTH        = 8,
    parameter int          PACKET_BEATS_MAX        = 16,
    parameter int          DESC_FIFO_DEPTH         = 32,
    parameter int          EXTRACTION_WINDOW_BYTES = 256,
    parameter int          EVENT_FIFO_DEPTH        = 16,
    parameter int          ORDER_TABLE_DEPTH       = 16,
    parameter logic [31:0] BUILD_ID                = 32'h4d50_5253
) (
    input  wire logic         rx_clk,
    input  wire logic         init_clk,
    input  wire logic         drp_clk,
    input  wire logic         sys_reset,

    input  wire logic         gt_ref_clk_p,
    input  wire logic         gt_ref_clk_n,
    input  wire logic [ 9:0]  gt_rxp_in,
    input  wire logic [ 9:0]  gt_rxn_in,
    output logic [ 9:0]       gt_txp_out,
    output logic [ 9:0]       gt_txn_out,

    output logic              gt_txusrclk2,
    output logic              gt_ref_clk_out,
    output logic [ 9:0]       gt_rxrecclkout,
    output logic [ 9:0]       gt_powergoodout,
    output logic              gt_rxusrclk2,

    output logic              usr_rx_reset,
    output logic              usr_tx_reset,
    output logic              stat_rx_aligned,
    output logic              stat_rx_status,
    output logic              stat_rx_local_fault,
    output logic              stat_rx_remote_fault,
    output logic              stat_rx_received_local_fault,
    output logic              tx_axis_tready,
    output logic              tx_ovfout,
    output logic              tx_unfout,
    output logic [15:0]       drp_do,
    output logic              drp_rdy,

    output logic              quote_valid,
    input  wire logic         quote_ready,
    output logic [15:0]       quote_stock_locate,
    output logic [31:0]       quote_bid_price,
    output logic [31:0]       quote_bid_shares,
    output logic [31:0]       quote_ask_price,
    output logic [31:0]       quote_ask_shares,
    output logic [47:0]       quote_timestamp,

    input  wire logic [11:0]  s_axi_awaddr,
    input  wire logic         s_axi_awvalid,
    output logic              s_axi_awready,
    input  wire logic [31:0]  s_axi_wdata,
    input  wire logic [ 3:0]  s_axi_wstrb,
    input  wire logic         s_axi_wvalid,
    output logic              s_axi_wready,
    output logic [ 1:0]       s_axi_bresp,
    output logic              s_axi_bvalid,
    input  wire logic         s_axi_bready,
    input  wire logic [11:0]  s_axi_araddr,
    input  wire logic         s_axi_arvalid,
    output logic              s_axi_arready,
    output logic [31:0]       s_axi_rdata,
    output logic [ 1:0]       s_axi_rresp,
    output logic              s_axi_rvalid,
    input  wire logic         s_axi_rready,

    output logic [31:0]       cmac_axis_accepted_packet_count,
    output logic [31:0]       cmac_axis_overflow_packet_count,
    output logic [31:0]       cmac_axis_dropped_beat_count,
    output logic [15:0]       cmac_axis_fifo_level,
    output logic [15:0]       cmac_axis_buffered_packet_count,

    output logic [31:0]       cmac_accepted_frame_count,
    output logic [31:0]       cmac_dropped_frame_count,
    output logic [31:0]       cmac_header_error_count,
    output logic [31:0]       cmac_payload_packet_count,
    output logic [15:0]       cmac_payload_fifo_level,

    output logic [31:0]       book_accepted_event_count,
    output logic [31:0]       book_applied_event_count,
    output logic [31:0]       book_ignored_event_count,
    output logic [31:0]       book_table_overflow_count,
    output logic [31:0]       book_quote_update_count
);
    logic         rx_axis_tvalid;
    logic [511:0] rx_axis_tdata;
    logic [ 63:0] rx_axis_tkeep;
    logic         rx_axis_tlast;
    logic         rx_axis_tuser;
    logic         parser_rst;

    assign parser_rst = sys_reset | usr_rx_reset;

    cmac_usplus_0 cmac_ip_i (
        .gt_txp_out                 (gt_txp_out),
        .gt_txn_out                 (gt_txn_out),
        .gt_rxp_in                  (gt_rxp_in),
        .gt_rxn_in                  (gt_rxn_in),
        .gt_txusrclk2               (gt_txusrclk2),
        .gt_loopback_in             (30'd0),
        .gt_ref_clk_out             (gt_ref_clk_out),
        .gt_rxrecclkout             (gt_rxrecclkout),
        .gt_powergoodout            (gt_powergoodout),
        .gtwiz_reset_tx_datapath    (sys_reset),
        .gtwiz_reset_rx_datapath    (sys_reset),
        .sys_reset                  (sys_reset),
        .gt_ref_clk_p               (gt_ref_clk_p),
        .gt_ref_clk_n               (gt_ref_clk_n),
        .init_clk                   (init_clk),
        .rx_axis_tvalid             (rx_axis_tvalid),
        .rx_axis_tdata              (rx_axis_tdata),
        .rx_axis_tlast              (rx_axis_tlast),
        .rx_axis_tkeep              (rx_axis_tkeep),
        .rx_axis_tuser              (rx_axis_tuser),
        .usr_rx_reset               (usr_rx_reset),
        .gt_rxusrclk2               (gt_rxusrclk2),
        .stat_rx_aligned            (stat_rx_aligned),
        .ctl_rx_check_etype_gcp     (1'b0),
        .ctl_rx_check_etype_gpp     (1'b0),
        .ctl_rx_check_etype_pcp     (1'b0),
        .ctl_rx_check_etype_ppp     (1'b0),
        .ctl_rx_check_mcast_gcp     (1'b0),
        .ctl_rx_check_mcast_gpp     (1'b0),
        .ctl_rx_check_mcast_pcp     (1'b0),
        .ctl_rx_check_mcast_ppp     (1'b0),
        .ctl_rx_check_opcode_gcp    (1'b0),
        .ctl_rx_check_opcode_gpp    (1'b0),
        .ctl_rx_check_opcode_pcp    (1'b0),
        .ctl_rx_check_opcode_ppp    (1'b0),
        .ctl_rx_check_sa_gcp        (1'b0),
        .ctl_rx_check_sa_gpp        (1'b0),
        .ctl_rx_check_sa_pcp        (1'b0),
        .ctl_rx_check_sa_ppp        (1'b0),
        .ctl_rx_check_ucast_gcp     (1'b0),
        .ctl_rx_check_ucast_gpp     (1'b0),
        .ctl_rx_check_ucast_pcp     (1'b0),
        .ctl_rx_check_ucast_ppp     (1'b0),
        .ctl_rx_enable_gcp          (1'b0),
        .ctl_rx_enable_gpp          (1'b0),
        .ctl_rx_enable_pcp          (1'b0),
        .ctl_rx_enable_ppp          (1'b0),
        .ctl_rx_pause_ack           (9'd0),
        .ctl_rx_pause_enable        (9'd0),
        .ctl_rx_enable              (1'b1),
        .ctl_rx_force_resync        (1'b0),
        .ctl_rx_test_pattern        (1'b0),
        .core_rx_reset              (sys_reset),
        .rx_clk                     (rx_clk),
        .stat_rx_received_local_fault(stat_rx_received_local_fault),
        .stat_rx_remote_fault       (stat_rx_remote_fault),
        .stat_rx_status             (stat_rx_status),
        .stat_rx_local_fault        (stat_rx_local_fault),
        .ctl_tx_enable              (1'b1),
        .ctl_tx_send_idle           (1'b0),
        .ctl_tx_send_rfi            (1'b0),
        .ctl_tx_send_lfi            (1'b0),
        .ctl_tx_test_pattern        (1'b0),
        .core_tx_reset              (sys_reset),
        .ctl_tx_pause_enable        (9'd0),
        .ctl_tx_pause_quanta0       (16'd0),
        .ctl_tx_pause_quanta1       (16'd0),
        .ctl_tx_pause_quanta2       (16'd0),
        .ctl_tx_pause_quanta3       (16'd0),
        .ctl_tx_pause_quanta4       (16'd0),
        .ctl_tx_pause_quanta5       (16'd0),
        .ctl_tx_pause_quanta6       (16'd0),
        .ctl_tx_pause_quanta7       (16'd0),
        .ctl_tx_pause_quanta8       (16'd0),
        .ctl_tx_pause_refresh_timer0(16'd0),
        .ctl_tx_pause_refresh_timer1(16'd0),
        .ctl_tx_pause_refresh_timer2(16'd0),
        .ctl_tx_pause_refresh_timer3(16'd0),
        .ctl_tx_pause_refresh_timer4(16'd0),
        .ctl_tx_pause_refresh_timer5(16'd0),
        .ctl_tx_pause_refresh_timer6(16'd0),
        .ctl_tx_pause_refresh_timer7(16'd0),
        .ctl_tx_pause_refresh_timer8(16'd0),
        .ctl_tx_pause_req           (9'd0),
        .ctl_tx_resend_pause        (1'b0),
        .tx_axis_tready             (tx_axis_tready),
        .tx_axis_tvalid             (1'b0),
        .tx_axis_tdata              (512'd0),
        .tx_axis_tlast              (1'b0),
        .tx_axis_tkeep              (64'd0),
        .tx_axis_tuser              (1'b0),
        .tx_ovfout                  (tx_ovfout),
        .tx_unfout                  (tx_unfout),
        .tx_preamblein              (56'd0),
        .usr_tx_reset               (usr_tx_reset),
        .core_drp_reset             (sys_reset),
        .drp_clk                    (drp_clk),
        .drp_addr                   (10'd0),
        .drp_di                     (16'd0),
        .drp_en                     (1'b0),
        .drp_do                     (drp_do),
        .drp_rdy                    (drp_rdy),
        .drp_we                     (1'b0)
    );

    market_parser_100g_cmac_axis_strategy_top #(
        .FEED_UDP_PORT          (FEED_UDP_PORT),
        .TARGET_STOCK_LOCATE    (TARGET_STOCK_LOCATE),
        .CMAC_RX_FIFO_DEPTH     (CMAC_RX_FIFO_DEPTH),
        .STRIP_FIFO_DEPTH       (STRIP_FIFO_DEPTH),
        .PACKET_BEATS_MAX       (PACKET_BEATS_MAX),
        .DESC_FIFO_DEPTH        (DESC_FIFO_DEPTH),
        .EXTRACTION_WINDOW_BYTES(EXTRACTION_WINDOW_BYTES),
        .EVENT_FIFO_DEPTH       (EVENT_FIFO_DEPTH),
        .ORDER_TABLE_DEPTH      (ORDER_TABLE_DEPTH),
        .BUILD_ID               (BUILD_ID)
    ) strategy_top_i (
        .clk                            (rx_clk),
        .rst                            (parser_rst),
        .rx_axis_tvalid                 (rx_axis_tvalid),
        .rx_axis_tdata                  (rx_axis_tdata),
        .rx_axis_tkeep                  (rx_axis_tkeep),
        .rx_axis_tlast                  (rx_axis_tlast),
        .rx_axis_tuser                  (rx_axis_tuser),
        .quote_valid                    (quote_valid),
        .quote_ready                    (quote_ready),
        .quote_stock_locate             (quote_stock_locate),
        .quote_bid_price                (quote_bid_price),
        .quote_bid_shares               (quote_bid_shares),
        .quote_ask_price                (quote_ask_price),
        .quote_ask_shares               (quote_ask_shares),
        .quote_timestamp                (quote_timestamp),
        .s_axi_awaddr                   (s_axi_awaddr),
        .s_axi_awvalid                  (s_axi_awvalid),
        .s_axi_awready                  (s_axi_awready),
        .s_axi_wdata                    (s_axi_wdata),
        .s_axi_wstrb                    (s_axi_wstrb),
        .s_axi_wvalid                   (s_axi_wvalid),
        .s_axi_wready                   (s_axi_wready),
        .s_axi_bresp                    (s_axi_bresp),
        .s_axi_bvalid                   (s_axi_bvalid),
        .s_axi_bready                   (s_axi_bready),
        .s_axi_araddr                   (s_axi_araddr),
        .s_axi_arvalid                  (s_axi_arvalid),
        .s_axi_arready                  (s_axi_arready),
        .s_axi_rdata                    (s_axi_rdata),
        .s_axi_rresp                    (s_axi_rresp),
        .s_axi_rvalid                   (s_axi_rvalid),
        .s_axi_rready                   (s_axi_rready),
        .cmac_axis_accepted_packet_count(cmac_axis_accepted_packet_count),
        .cmac_axis_overflow_packet_count(cmac_axis_overflow_packet_count),
        .cmac_axis_dropped_beat_count   (cmac_axis_dropped_beat_count),
        .cmac_axis_fifo_level           (cmac_axis_fifo_level),
        .cmac_axis_buffered_packet_count(cmac_axis_buffered_packet_count),
        .cmac_accepted_frame_count      (cmac_accepted_frame_count),
        .cmac_dropped_frame_count       (cmac_dropped_frame_count),
        .cmac_header_error_count        (cmac_header_error_count),
        .cmac_payload_packet_count      (cmac_payload_packet_count),
        .cmac_payload_fifo_level        (cmac_payload_fifo_level),
        .book_accepted_event_count      (book_accepted_event_count),
        .book_applied_event_count       (book_applied_event_count),
        .book_ignored_event_count       (book_ignored_event_count),
        .book_table_overflow_count      (book_table_overflow_count),
        .book_quote_update_count        (book_quote_update_count)
    );

endmodule
`default_nettype wire
