`default_nettype none
// Complete source-only market-data path through decision and venue-neutral
// order lifecycle management. Exchange responses close the position-risk loop.
module market_parser_100g_cmac_axis_order_top #(
    parameter logic [15:0] FEED_UDP_PORT = 16'd5000,
    parameter int NUM_SYMBOLS = 4,
    parameter logic [NUM_SYMBOLS*16-1:0] SYMBOL_LOCATES = {
        16'h4444, 16'h3333, 16'h2222, 16'h1111
    },
    parameter int CMAC_RX_FIFO_DEPTH = 64,
    parameter int STRIP_FIFO_DEPTH = 8,
    parameter int PACKET_BEATS_MAX = 32,
    parameter int DESC_FIFO_DEPTH = 32,
    parameter int EXTRACTION_WINDOW_BYTES = 256,
    parameter int EVENT_FIFO_DEPTH = 16,
    parameter int ORDER_TABLE_DEPTH = 16,
    parameter logic [31:0] BUILD_ID = 32'h4d50_5253,
    parameter logic [31:0] FEED_TIMEOUT_CYCLES_DEFAULT = 32'd322_400_000
) (
    input  wire logic                         clk,
    input  wire logic                         rst,
    input  wire logic                         feed_recover,
    input  wire logic                         feed_activate,
    input  wire logic                         rx_axis_tvalid,
    input  wire logic [511:0]                 rx_axis_tdata,
    input  wire logic [ 63:0]                 rx_axis_tkeep,
    input  wire logic                         rx_axis_tlast,
    input  wire logic                         rx_axis_tuser,

    input  wire logic                         strategy_enable,
    input  wire logic                         kill_switch,
    input  wire logic                         position_clear,
    input  wire logic [31:0]                  max_spread_ticks,
    input  wire logic [31:0]                  min_top_shares,
    input  wire logic [ 2:0]                  imbalance_shift,
    input  wire logic [31:0]                  order_quantity,
    input  wire logic [31:0]                  max_abs_position,

    output logic                              order_cmd_valid,
    input  wire logic                         order_cmd_ready,
    output logic                              order_cmd_cancel,
    output logic [63:0]                       order_cmd_id,
    output logic [15:0]                       order_cmd_stock_locate,
    output logic                              order_cmd_side,
    output logic [31:0]                       order_cmd_price,
    output logic [31:0]                       order_cmd_quantity,
    output logic [47:0]                       order_cmd_timestamp,

    input  wire logic                         exchange_event_valid,
    output logic                              exchange_event_ready,
    input  wire logic [ 1:0]                  exchange_event_type,
    input  wire logic [63:0]                  exchange_event_order_id,
    input  wire logic [31:0]                  exchange_event_price,
    input  wire logic [31:0]                  exchange_event_quantity,

    input  wire logic [11:0]                  s_axi_awaddr,
    input  wire logic                         s_axi_awvalid,
    output logic                              s_axi_awready,
    input  wire logic [31:0]                  s_axi_wdata,
    input  wire logic [ 3:0]                  s_axi_wstrb,
    input  wire logic                         s_axi_wvalid,
    output logic                              s_axi_wready,
    output logic [ 1:0]                       s_axi_bresp,
    output logic                              s_axi_bvalid,
    input  wire logic                         s_axi_bready,
    input  wire logic [11:0]                  s_axi_araddr,
    input  wire logic                         s_axi_arvalid,
    output logic                              s_axi_arready,
    output logic [31:0]                       s_axi_rdata,
    output logic [ 1:0]                       s_axi_rresp,
    output logic                              s_axi_rvalid,
    input  wire logic                         s_axi_rready,

    output logic [NUM_SYMBOLS*32-1:0]         position_by_symbol,
    output logic [NUM_SYMBOLS-1:0]            working_order_mask,
    output logic [NUM_SYMBOLS-1:0]            live_order_mask,
    output logic [NUM_SYMBOLS*32-1:0]         leaves_quantity_by_symbol,
    output logic [15:0]                       outstanding_order_count,
    output logic [31:0]                       accepted_intent_count,
    output logic [31:0]                       busy_intent_count,
    output logic [31:0]                       untracked_intent_count,
    output logic [31:0]                       new_command_count,
    output logic [31:0]                       acknowledged_order_count,
    output logic [31:0]                       rejected_order_count,
    output logic [31:0]                       cancel_command_count,
    output logic [31:0]                       cancel_ack_count,
    output logic [31:0]                       lifecycle_fill_count,
    output logic [31:0]                       canceled_before_send_count,
    output logic [31:0]                       protocol_error_count,
    output logic [31:0]                       evaluated_quote_count,
    output logic [31:0]                       generated_intent_count,
    output logic [31:0]                       control_suppressed_count,
    output logic [31:0]                       market_suppressed_count,
    output logic [31:0]                       risk_suppressed_count,
    output logic [31:0]                       applied_fill_count,
    output logic [31:0]                       untracked_fill_count,
    output logic [31:0]                       cmac_axis_accepted_packet_count,
    output logic [31:0]                       cmac_axis_overflow_packet_count,
    output logic [31:0]                       cmac_axis_dropped_beat_count,
    output logic [31:0]                       book_quote_update_count,
    output logic                              feed_healthy,
    output logic                              feed_rebuilding,
    output logic [31:0]                       feed_gap_count,
    output logic [31:0]                       feed_timeout_count
);
    logic        intent_valid;
    logic        intent_ready;
    logic [15:0] intent_stock_locate;
    logic        intent_side;
    logic [31:0] intent_price;
    logic [31:0] intent_quantity;
    logic [47:0] intent_timestamp;

    logic        lifecycle_fill_valid;
    logic [15:0] lifecycle_fill_stock_locate;
    logic        lifecycle_fill_side;
    logic [31:0] lifecycle_fill_quantity;

    logic lifecycle_trading_enabled;
    logic lifecycle_cancel_all;

    assign lifecycle_trading_enabled =
        feed_healthy && strategy_enable && !kill_switch;
    assign lifecycle_cancel_all =
        !feed_healthy || !strategy_enable || kill_switch;

    market_parser_100g_cmac_axis_decision_top #(
        .FEED_UDP_PORT(FEED_UDP_PORT),
        .NUM_SYMBOLS(NUM_SYMBOLS),
        .SYMBOL_LOCATES(SYMBOL_LOCATES),
        .CMAC_RX_FIFO_DEPTH(CMAC_RX_FIFO_DEPTH),
        .STRIP_FIFO_DEPTH(STRIP_FIFO_DEPTH),
        .PACKET_BEATS_MAX(PACKET_BEATS_MAX),
        .DESC_FIFO_DEPTH(DESC_FIFO_DEPTH),
        .EXTRACTION_WINDOW_BYTES(EXTRACTION_WINDOW_BYTES),
        .EVENT_FIFO_DEPTH(EVENT_FIFO_DEPTH),
        .ORDER_TABLE_DEPTH(ORDER_TABLE_DEPTH),
        .BUILD_ID(BUILD_ID),
        .FEED_TIMEOUT_CYCLES_DEFAULT(FEED_TIMEOUT_CYCLES_DEFAULT)
    ) decision_top_i (
        .clk(clk),
        .rst(rst),
        .feed_recover(feed_recover),
        .feed_activate(feed_activate),
        .rx_axis_tvalid(rx_axis_tvalid),
        .rx_axis_tdata(rx_axis_tdata),
        .rx_axis_tkeep(rx_axis_tkeep),
        .rx_axis_tlast(rx_axis_tlast),
        .rx_axis_tuser(rx_axis_tuser),
        .strategy_enable(strategy_enable),
        .kill_switch(kill_switch),
        .position_clear(position_clear),
        .max_spread_ticks(max_spread_ticks),
        .min_top_shares(min_top_shares),
        .imbalance_shift(imbalance_shift),
        .order_quantity(order_quantity),
        .max_abs_position(max_abs_position),
        .fill_valid(lifecycle_fill_valid),
        .fill_stock_locate(lifecycle_fill_stock_locate),
        .fill_side(lifecycle_fill_side),
        .fill_quantity(lifecycle_fill_quantity),
        .intent_valid(intent_valid),
        .intent_ready(intent_ready),
        .intent_stock_locate(intent_stock_locate),
        .intent_side(intent_side),
        .intent_price(intent_price),
        .intent_quantity(intent_quantity),
        .intent_timestamp(intent_timestamp),
        .position_by_symbol(position_by_symbol),
        .evaluated_quote_count(evaluated_quote_count),
        .generated_intent_count(generated_intent_count),
        .control_suppressed_count(control_suppressed_count),
        .market_suppressed_count(market_suppressed_count),
        .risk_suppressed_count(risk_suppressed_count),
        .applied_fill_count(applied_fill_count),
        .untracked_fill_count(untracked_fill_count),
        .s_axi_awaddr(s_axi_awaddr),
        .s_axi_awvalid(s_axi_awvalid),
        .s_axi_awready(s_axi_awready),
        .s_axi_wdata(s_axi_wdata),
        .s_axi_wstrb(s_axi_wstrb),
        .s_axi_wvalid(s_axi_wvalid),
        .s_axi_wready(s_axi_wready),
        .s_axi_bresp(s_axi_bresp),
        .s_axi_bvalid(s_axi_bvalid),
        .s_axi_bready(s_axi_bready),
        .s_axi_araddr(s_axi_araddr),
        .s_axi_arvalid(s_axi_arvalid),
        .s_axi_arready(s_axi_arready),
        .s_axi_rdata(s_axi_rdata),
        .s_axi_rresp(s_axi_rresp),
        .s_axi_rvalid(s_axi_rvalid),
        .s_axi_rready(s_axi_rready),
        .cmac_axis_accepted_packet_count(cmac_axis_accepted_packet_count),
        .cmac_axis_overflow_packet_count(cmac_axis_overflow_packet_count),
        .cmac_axis_dropped_beat_count(cmac_axis_dropped_beat_count),
        .cmac_axis_fifo_level(),
        .cmac_axis_fifo_high_watermark(),
        .cmac_axis_buffered_packet_count(),
        .book_accepted_event_count(),
        .book_applied_event_count(),
        .book_ignored_event_count(),
        .book_untracked_event_count(),
        .book_table_overflow_count(),
        .book_quote_update_count(book_quote_update_count),
        .feed_healthy(feed_healthy),
        .feed_rebuilding(feed_rebuilding),
        .feed_rebuild_ready(),
        .feed_gap_count(feed_gap_count),
        .feed_suppressed_event_count(),
        .feed_idle_cycles(),
        .feed_timeout_count(feed_timeout_count),
        .feed_activation_reject_count(),
        .feed_session_change_count(),
        .feed_end_of_session_count()
    );

    market_parser_order_manager #(
        .NUM_SYMBOLS(NUM_SYMBOLS),
        .SYMBOL_LOCATES(SYMBOL_LOCATES)
    ) order_manager_i (
        .clk(clk),
        .rst(rst),
        .trading_enabled(lifecycle_trading_enabled),
        .cancel_all(lifecycle_cancel_all),
        .intent_valid(intent_valid),
        .intent_ready(intent_ready),
        .intent_stock_locate(intent_stock_locate),
        .intent_side(intent_side),
        .intent_price(intent_price),
        .intent_quantity(intent_quantity),
        .intent_timestamp(intent_timestamp),
        .order_cmd_valid(order_cmd_valid),
        .order_cmd_ready(order_cmd_ready),
        .order_cmd_cancel(order_cmd_cancel),
        .order_cmd_id(order_cmd_id),
        .order_cmd_stock_locate(order_cmd_stock_locate),
        .order_cmd_side(order_cmd_side),
        .order_cmd_price(order_cmd_price),
        .order_cmd_quantity(order_cmd_quantity),
        .order_cmd_timestamp(order_cmd_timestamp),
        .exchange_event_valid(exchange_event_valid),
        .exchange_event_ready(exchange_event_ready),
        .exchange_event_type(exchange_event_type),
        .exchange_event_order_id(exchange_event_order_id),
        .exchange_event_price(exchange_event_price),
        .exchange_event_quantity(exchange_event_quantity),
        .fill_valid(lifecycle_fill_valid),
        .fill_stock_locate(lifecycle_fill_stock_locate),
        .fill_side(lifecycle_fill_side),
        .fill_price(),
        .fill_quantity(lifecycle_fill_quantity),
        .working_order_mask(working_order_mask),
        .live_order_mask(live_order_mask),
        .leaves_quantity_by_symbol(leaves_quantity_by_symbol),
        .outstanding_order_count(outstanding_order_count),
        .accepted_intent_count(accepted_intent_count),
        .busy_intent_count(busy_intent_count),
        .untracked_intent_count(untracked_intent_count),
        .new_command_count(new_command_count),
        .acknowledged_order_count(acknowledged_order_count),
        .rejected_order_count(rejected_order_count),
        .cancel_command_count(cancel_command_count),
        .cancel_ack_count(cancel_ack_count),
        .fill_event_count(lifecycle_fill_count),
        .canceled_before_send_count(canceled_before_send_count),
        .protocol_error_count(protocol_error_count)
    );

endmodule
`default_nettype wire
