cd ..
onerror {quit -code 1}
if {[file exists work]} {
    vdel -lib work -all
}
vlib work
vlog -sv rtl/market_parser_pkg.sv rtl/market_parser.sv rtl/market_parser_axis_adapter.sv rtl/market_parser_64.sv rtl/market_parser_axis_register_slice.sv rtl/market_parser_100g_ingress.sv rtl/market_parser_udp_payload_strip.sv rtl/market_parser_512_boundary_scan.sv rtl/market_parser_512_frontend.sv rtl/market_parser_512_event_extract.sv rtl/market_parser_512_window_buffer.sv rtl/market_parser_512_pipeline.sv rtl/market_parser_event_fifo.sv rtl/market_parser_512_pipeline_fifo.sv rtl/market_parser_axi_lite_regs.sv rtl/market_parser_512_system.sv rtl/market_parser_100g_cmac_system.sv rtl/market_parser_top_of_book.sv rtl/market_parser_multi_symbol_top_of_book.sv rtl/market_parser_100g_strategy_top.sv rtl/market_parser_100g_multi_strategy_top.sv rtl/market_parser_cmac_axis_rx_bridge.sv rtl/market_parser_100g_cmac_axis_strategy_top.sv rtl/market_parser_100g_cmac_axis_multi_strategy_top.sv rtl/market_parser_signal_engine.sv rtl/market_parser_100g_cmac_axis_decision_top.sv rtl/market_parser_order_manager.sv rtl/market_parser_order_risk_guard.sv rtl/market_parser_ouch5_codec.sv rtl/market_parser_soupbintcp_client.sv rtl/market_parser_100g_cmac_axis_order_top.sv rtl/market_parser_100g_cmac_axis_egress_top.sv rtl/market_parser_100g_strategy_impl_harness.sv rtl/market_parser_100g_cmac_axis_impl_harness.sv rtl/market_parser_100g_cmac_axis_decision_impl_harness.sv rtl/market_parser_100g_cmac_axis_order_impl_harness.sv rtl/market_parser_100g_cmac_axis_egress_impl_harness.sv verification/market_parser_tb.sv verification/market_parser_64_tb.sv verification/market_parser_axis_adapter_tb.sv verification/market_parser_100g_ingress_tb.sv verification/market_parser_100g_cmac_system_tb.sv verification/market_parser_cmac_axis_rx_bridge_tb.sv verification/market_parser_512_boundary_scan_tb.sv verification/market_parser_512_frontend_tb.sv verification/market_parser_512_event_extract_tb.sv verification/market_parser_512_pipeline_tb.sv verification/market_parser_512_pipeline_fifo_tb.sv verification/market_parser_512_system_tb.sv verification/market_parser_top_of_book_tb.sv verification/market_parser_multi_symbol_top_of_book_tb.sv verification/market_parser_100g_strategy_top_tb.sv verification/market_parser_100g_multi_strategy_top_tb.sv verification/market_parser_signal_engine_tb.sv verification/market_parser_100g_cmac_axis_decision_top_tb.sv verification/market_parser_order_manager_tb.sv verification/market_parser_order_risk_guard_tb.sv verification/market_parser_order_risk_integration_tb.sv verification/market_parser_ouch5_codec_tb.sv verification/market_parser_soupbintcp_client_tb.sv verification/market_parser_100g_cmac_axis_order_top_tb.sv verification/market_parser_100g_cmac_axis_decision_impl_harness_tb.sv verification/market_parser_100g_cmac_axis_order_impl_harness_tb.sv verification/market_parser_100g_cmac_axis_egress_impl_harness_tb.sv

proc run_test {args} {
    eval vsim -onfinish stop $args
    run -all
    set status [runStatus -full]
    if {[llength $status] < 3 || [lindex $status 2] ne {$finish}} {
        puts stderr "REGRESSION ERROR: $args stopped with status: $status"
        quit -code 1
    }
    quit -sim
}

vlog -sv rtl/market_parser_order_command_fifo.sv rtl/market_parser_ouch5_gateway.sv rtl/market_parser_order_latency_monitor.sv rtl/market_parser_100g_ouch5_top.sv rtl/market_parser_100g_ouch5_impl_harness.sv verification/market_parser_order_command_fifo_tb.sv verification/market_parser_ouch5_gateway_tb.sv verification/market_parser_order_latency_monitor_tb.sv verification/market_parser_100g_ouch5_top_tb.sv verification/market_parser_100g_ouch5_impl_harness_tb.sv

run_test market_parser_tb
run_test market_parser_64_tb
run_test -GDATA_WIDTH=64 market_parser_axis_adapter_tb
run_test -GDATA_WIDTH=256 market_parser_axis_adapter_tb
run_test -GDATA_WIDTH=512 market_parser_axis_adapter_tb
run_test market_parser_100g_ingress_tb
run_test market_parser_100g_cmac_system_tb
run_test market_parser_cmac_axis_rx_bridge_tb
run_test market_parser_512_boundary_scan_tb
run_test market_parser_512_frontend_tb
run_test market_parser_512_event_extract_tb
run_test -GEXTRACTION_WINDOW_BYTES=128 market_parser_512_pipeline_tb
run_test -GEXTRACTION_WINDOW_BYTES=256 market_parser_512_pipeline_tb
run_test -GEXTRACTION_WINDOW_BYTES=512 market_parser_512_pipeline_tb
run_test market_parser_512_pipeline_fifo_tb
run_test market_parser_512_system_tb
run_test market_parser_top_of_book_tb
run_test market_parser_multi_symbol_top_of_book_tb
run_test market_parser_100g_strategy_top_tb
run_test market_parser_100g_multi_strategy_top_tb
run_test market_parser_signal_engine_tb
run_test market_parser_100g_cmac_axis_decision_top_tb
run_test market_parser_order_manager_tb
run_test market_parser_order_risk_guard_tb
run_test market_parser_order_risk_integration_tb
run_test market_parser_ouch5_codec_tb
run_test market_parser_soupbintcp_client_tb
run_test market_parser_order_command_fifo_tb
run_test market_parser_ouch5_gateway_tb
run_test market_parser_order_latency_monitor_tb
run_test market_parser_100g_ouch5_top_tb
run_test market_parser_100g_ouch5_impl_harness_tb
run_test market_parser_100g_cmac_axis_order_top_tb
run_test market_parser_100g_cmac_axis_decision_impl_harness_tb
run_test market_parser_100g_cmac_axis_order_impl_harness_tb
run_test market_parser_100g_cmac_axis_egress_impl_harness_tb
quit -code 0
