localparam int TOP_BOOK_REPLAY_RAW_PACKET_BYTES = 545;
localparam int TOP_BOOK_REPLAY_EXPECTED_RAW_BEATS = 9;
localparam int TOP_BOOK_REPLAY_EXPECTED_EVENTS = 15;
localparam int TOP_BOOK_REPLAY_EXPECTED_QUOTES = 7;
localparam int TOP_BOOK_REPLAY_EXPECTED_APPLIED = 11;
localparam int TOP_BOOK_REPLAY_EXPECTED_IGNORED = 4;
localparam int TOP_BOOK_REPLAY_EXPECTED_OVERFLOW = 0;
